<?php
return array(
    'alnum',
    'alpha',
    'between',
    'charset',
    'consonant',
    'contains',
    'cntrl',
    'digit',
    'ends_with'         => 'endsWith',
    'in',
    'graph',
    'length',
    'lowercase',
    'not_empty'         => 'notEmpty',
    'no_whitespace'     => 'noWhitespace',
    'prnt',
    'punct',
    'regex',
    'slug',
    'space',
    'starts_with'        => 'startsWith',
    'uppercase',
    'uppercase',
    'version',
    'vowel',
    'xdigit',    
);